version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        command: sudo chmod +x ./gradlew
    - run:
        name: Build Release
        command: ./gradlew -PvCode=$CIRCLE_BUILD_NUM assembleRelease
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - store_artifacts:
        path: ~/code/app/build/outputs/apk/release
        destination: release